### ISSUE TITLE
Incorporate signing into release pipeline

### ISSUE THREAD

**Issue by swinton** [swinton/device-flow#6]
## Resources
- https://goreleaser.com/customization/sign/
- https://goreleaser.com/customization/sign/#executables

## Examples

```yaml
builds:
- binary: foo
  id: foo
  goos:
  - linux
  - windows
  goarch:
  - amd64

# notice that we need a separated build for the MacOS binary only:
- binary: foo
  id: foo-macos
  goos:
  - darwin
  goarch:
  - amd64
  hooks:
    post: gon gon.hcl
```

```hcl
# The path follows a pattern
# ./dist/BUILD-ID_TARGET/BINARY-NAME
source = ["./dist/foo-macos_darwin_amd64/foo"]
bundle_id = "com.mitchellh.example.terraform"

apple_id {
  username = "mitchell@example.com"
  password = "@env:AC_PASSWORD"
}

sign {
  application_identity = "Developer ID Application: Mitchell Hashimoto"
}
```

## Other

Test with a local only release:

```shell
goreleaser release --snapshot --skip-publish --rm-dist
```
